[tool.bumpversion]
current_version = "5.4.0"

[[tool.bumpversion.files]]
filename = "INSTALLING.rst"
search = "hoomd={current_version}"
replace = "hoomd={new_version}"

[[tool.bumpversion.files]]
filename = "CMakeLists.txt"
search = 'HOOMD_VERSION_RAW "{current_version}"'
replace = 'HOOMD_VERSION_RAW "{new_version}"'

[[tool.bumpversion.files]]
filename = "sphinx-doc/conf.py"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "sphinx-doc/conf.py"
search = 'release = "{current_version}"'
replace = 'release = "{new_version}"'

[[tool.bumpversion.files]]
filename = ".github/ISSUE_TEMPLATE/bug_report.yml"
search = """
      description: What version of HOOMD-blue are you using?
      placeholder: {current_version}"""

replace = """
      description: What version of HOOMD-blue are you using?
      placeholder: {new_version}"""

[[tool.bumpversion.files]]
filename = ".github/ISSUE_TEMPLATE/release.md"
search = "Release {current_version}"
replace = "Release {new_version}"

[[tool.bumpversion.files]]
filename = "CHANGELOG.rst"
regex = true
search = 'Next release$'
replace = '{new_version} ({now:%Y-%m-%d})'
