version: 2

python:
   install:
   - requirements: sphinx-doc/requirements.txt

sphinx:
  configuration: sphinx-doc/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

submodules:
  include: all
