name: Bug report
description: Report a problem with HOOMD-blue.
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Script
      description: |
        The *minimal* script that demonstrates the problem. The script should depend only on
        HOOMD-blue and its dependencies so that developers can run it.
      placeholder: |
        import hoomd
        ...
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input files
      description: Attach any input files needed to run the script.
  - type: textarea
    attributes:
      label: Output
      description: |
        What output did you get?
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected output
      description: What output do you expect?
  - type: dropdown
    attributes:
      label: Platform
      description: What platform are you using? Select all that apply.
      multiple: true
      options:
        - CPU
        - GPU
        - Linux
        - macOS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation method
      description: How did you install HOOMD-blue?
      options:
        - Compiled from source
        - Conda-forge package
        - glotzerlab-software package
    validations:
      required: true
  - type: input
    attributes:
      label: HOOMD-blue version
      description: What version of HOOMD-blue are you using?
      placeholder: 4.8.1
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Run `python3 -c "import hoomd; print(hoomd.version.version)"` to find your HOOMD-blue version.
  - type: input
    attributes:
      label: Python version
      description: What version of Python are you using?
      placeholder: 3.11.3
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Run `python3 --version` to find your Python version.
