pipeline
    {
    options { skipDefaultCheckout() }
    agent none

    stages
        {
        stage('gcc54-py27-cuda8')
            {
            agent { label 'gpu' }

            environment
                {
                CC = '/usr/bin/gcc'
                CXX = '/usr/bin/g++'
                OMP_NUM_THREADS = '1'
                }

            steps
                {
                sh 'echo ${NODE_NAME}'

                dir('code')
                    {
                    checkout scm
                    sh 'git submodule update --init'
                    }

                dir('build')
                    {
                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv /nfs/glotzer/containers/ci-2018.09-cuda8.simg /usr/bin/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python2.7 -DENABLE_CUDA=ON -DENABLE_MPI=OFF -DENABLE_TBB=OFF -DBUILD_VALIDATION=OFF -DBUILD_TESTING=ON -DTEST_CPU_IN_GPU_BUILDS=OFF -DBUILD_DEPRECATED=off -DBUILD_JIT=OFF -GNinja
                           '''

                        sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                        }

                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv ${CONTAINER} /usr/bin/ctest --no-compress-output -T test --output-on-failure
                           '''
                        }
                    }

                sh 'xsltproc code/.jenkins/ctest2junit.xsl build/Testing/**/Test.xml > ./test.xml'

                junit 'test.xml'
                }
            post
                {
                always
                    {
                    archive 'build/Testing/**/Test.xml'
                    deleteDir()
                    }
                }
            }
        stage('vld-gcc7-py36-mpi-cuda9')
            {
            agent { label 'gpu' }

            environment
                {
                CC = '/usr/bin/gcc-7'
                CXX = '/usr/bin/g++-7'
                OMP_NUM_THREADS = '1'
                }

            steps
                {
                sh 'echo ${NODE_NAME}'

                dir('code')
                    {
                    checkout scm
                    sh 'git submodule update --init'
                    }

                dir('build')
                    {
                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv /nfs/glotzer/containers/ci-2018.09-cuda9.simg /usr/sbin/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_CUDA=ON -DENABLE_MPI=ON -DENABLE_TBB=OFF -DBUILD_VALIDATION=ON -DBUILD_TESTING=ON -DTEST_CPU_IN_GPU_BUILDS=OFF -DBUILD_DEPRECATED=off -DBUILD_JIT=OFF -GNinja
                           '''

                        sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                        }

                    timeout(time: 15, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv ${CONTAINER} /usr/sbin/ctest --no-compress-output -T test --output-on-failure
                           '''
                        }
                    }

                sh 'xsltproc code/.jenkins/ctest2junit.xsl build/Testing/**/Test.xml > ./test.xml'

                junit 'test.xml'
                }
            post
                {
                always
                    {
                    archive 'build/Testing/**/Test.xml'
                    deleteDir()
                    }
                }
            }
        stage('vld-gcc6-py36-mpi')
            {
            agent { label 'linux-cpu' }

            environment
                {
                CC = '/usr/bin/gcc-6'
                CXX = '/usr/bin/g++-6'
                OMP_NUM_THREADS = '1'
                }

            steps
                {
                sh 'echo ${NODE_NAME}'

                dir('code')
                    {
                    checkout scm
                    sh 'git submodule update --init'
                    }

                dir('build')
                    {
                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv /nfs/glotzer/containers/ci-2018.09-ubuntu18.04.simg /usr/sbin/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_CUDA=OFF -DENABLE_MPI=ON -DENABLE_TBB=OFF -DBUILD_VALIDATION=ON -DBUILD_TESTING=OFF -DTEST_CPU_IN_GPU_BUILDS=OFF -DBUILD_DEPRECATED=off -DBUILD_JIT=ON -GNinja
                           '''

                        sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                        }

                    timeout(time: 15, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv ${CONTAINER} /usr/sbin/ctest --no-compress-output -T test --output-on-failure
                           '''
                        }
                    }

                sh 'xsltproc code/.jenkins/ctest2junit.xsl build/Testing/**/Test.xml > ./test.xml'

                junit 'test.xml'
                }
            post
                {
                always
                    {
                    archive 'build/Testing/**/Test.xml'
                    deleteDir()
                    }
                }
            }
        stage('vld-gcc7-py36-mpi-tbb1')
            {
            agent { label 'linux-cpu' }

            environment
                {
                CC = '/usr/bin/gcc-7'
                CXX = '/usr/bin/g++-7'
                OMP_NUM_THREADS = '1'
                }

            steps
                {
                sh 'echo ${NODE_NAME}'

                dir('code')
                    {
                    checkout scm
                    sh 'git submodule update --init'
                    }

                dir('build')
                    {
                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv /nfs/glotzer/containers/ci-2018.09-ubuntu18.04.simg /usr/sbin/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_CUDA=OFF -DENABLE_MPI=ON -DENABLE_TBB=ON -DBUILD_VALIDATION=ON -DBUILD_TESTING=OFF -DTEST_CPU_IN_GPU_BUILDS=OFF -DBUILD_DEPRECATED=off -DBUILD_JIT=ON -GNinja
                           '''

                        sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                        }

                    timeout(time: 15, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv ${CONTAINER} /usr/sbin/ctest --no-compress-output -T test --output-on-failure
                           '''
                        }
                    }

                sh 'xsltproc code/.jenkins/ctest2junit.xsl build/Testing/**/Test.xml > ./test.xml'

                junit 'test.xml'
                }
            post
                {
                always
                    {
                    archive 'build/Testing/**/Test.xml'
                    deleteDir()
                    }
                }
            }
        stage('vld-gcc8-py36-mpi-tbb3')
            {
            agent { label 'linux-cpu' }

            environment
                {
                CC = '/usr/bin/gcc-8'
                CXX = '/usr/bin/g++-8'
                OMP_NUM_THREADS = '3'
                }

            steps
                {
                sh 'echo ${NODE_NAME}'

                dir('code')
                    {
                    checkout scm
                    sh 'git submodule update --init'
                    }

                dir('build')
                    {
                    timeout(time: 1, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv /nfs/glotzer/containers/ci-2018.09-ubuntu18.04.simg /usr/sbin/cmake ../code -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DENABLE_CUDA=OFF -DENABLE_MPI=ON -DENABLE_TBB=ON -DBUILD_VALIDATION=ON -DBUILD_TESTING=OFF -DTEST_CPU_IN_GPU_BUILDS=OFF -DBUILD_DEPRECATED=off -DBUILD_JIT=ON -GNinja
                           '''

                        sh 'singularity exec --nv ${CONTAINER} ninja -j 3'
                        }

                    timeout(time: 15, unit: 'HOURS')
                        {
                        sh '''
                            singularity exec --nv ${CONTAINER} /usr/sbin/ctest --no-compress-output -T test --output-on-failure
                           '''
                        }
                    }

                sh 'xsltproc code/.jenkins/ctest2junit.xsl build/Testing/**/Test.xml > ./test.xml'

                junit 'test.xml'
                }
            post
                {
                always
                    {
                    archive 'build/Testing/**/Test.xml'
                    deleteDir()
                    }
                }
            }
        
        }
    }
