#! /usr/bin/env perl

open(IN, "<$ENV{HOME}/Documents/Papers/bib/HOOMD-doc.bib") or die("No input file");
open(OUT, '>doc/user/HOOMD.bib');

print OUT "This file is automatically generated by update_bib.pl from a bibtex database managed by Joshua Anderson\n";
print OUT "Please send him the doi of any reference you wish to add\n";
print OUT "\n";

$waiting = 0;
while (<IN>)
    {
    if (/^file/ || /^mendeley-tags/ || /^abstract/ || /^keywords/ || /^url/ || /^language/ || /^month/ || /^issn/ || /^doi/ || /^pmid/ || /^publisher/)
        {
        $waiting = 1;
        }
    if ($waiting)
        {
        if (/\}/)
            {
            $waiting = 0;
            next;
            }
        else
            {
            next;
            }
        }

    s/\}\}/\}/;
    s/\{\{/\{/;
    print OUT;
    }

